window.data = [
  {
    execStartTimeMs: 10,
    execEndTimeMs: 274,
    execTimeMs: 264,
    location: 'page',
    parentType: 'Query',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 276,
    execTimeMs: 1,
    location: 'page.zoneSets.1.zones.0.widgets.0.items',
    parentType: 'ArticleHeader',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 276,
    execTimeMs: 1,
    location: 'page.zoneSets.1.zones.0.widgets.1.items',
    parentType: 'ArticleBody',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 276,
    execTimeMs: 1,
    location: 'page.zoneSets.1.zones.0.widgets.2.items',
    parentType: 'ArticleFooter',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 278,
    execTimeMs: 1,
    location: 'page.zoneSets.1.zones.0.widgets.1.items.0.body',
    parentType: 'Article',
  },
  {
    execStartTimeMs: 276,
    execEndTimeMs: 279,
    execTimeMs: 2,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.breadcrumbs',
    parentType: 'Article',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 178,
    location: 'page.zoneSets.0.zones.0.widgets.0.type',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 178,
    location: 'page.zoneSets.1.zones.1.widgets.0.type',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 177,
    location: 'page.zoneSets.2.zones.0.widgets.0.type',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 178,
    location: 'page.zoneSets.0.zones.0.widgets.0.options',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 178,
    location: 'page.zoneSets.0.zones.0.widgets.0.items',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 178,
    location: 'page.zoneSets.1.zones.1.widgets.0.options',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 178,
    location: 'page.zoneSets.1.zones.1.widgets.0.items',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 177,
    location: 'page.zoneSets.2.zones.0.widgets.0.options',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 275,
    execEndTimeMs: 453,
    execTimeMs: 177,
    location: 'page.zoneSets.2.zones.0.widgets.0.items',
    parentType: 'Collection',
  },
  {
    execStartTimeMs: 276,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.title',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 276,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.biography',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 276,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.url',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 276,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.slug',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 276,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.email',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.facebook',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.linkedIn',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.twitter',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.hasContact',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.title',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.biography',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.url',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.slug',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.email',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.facebook',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.linkedIn',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.twitter',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.hasContact',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 265,
    location: 'page.zoneSets.1.zones.0.widgets.0.items.0.authors.0.image',
    parentType: 'Author',
  },
  {
    execStartTimeMs: 277,
    execEndTimeMs: 542,
    execTimeMs: 264,
    location: 'page.zoneSets.1.zones.0.widgets.2.items.0.authors.0.image',
    parentType: 'Author',
  },
];